### ISSUE TITLE
Install Failled

### ISSUE THREAD

**Issue by aemonge** [dongri/mongri#4]
```bash
λ antergos mongri → node app.js                                              λ git master|✔ →
Failed to load c++ bson extension, using pure JS version
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Object.<anonymous> (/home/aemonge/user/lib/workTools/mongri/app.js:148:24)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

```

**Comment by dongri** [comment]
hi @aemonge 
you can try `$ PORT=9090 node app.js` 
http://localhost:9090

http://stackoverflow.com/questions/9898372/nodejs-error-listen-eaddrinuse
